#!/bin/sh

REGISTRY=quay.io
REGISTRY_USER_ID=cvicensa
IMAGE_NAME=cnw-installer
IMAGE_VERSION=v0.0.1

docker build -t $REGISTRY/$REGISTRY_USER_ID/$IMAGE_NAME:$IMAGE_VERSION .

docker push $REGISTRY/$REGISTRY_USER_ID/$IMAGE_NAME:$IMAGE_VERSION