apiVersion: batch/v1
kind: Job
metadata:
  name: cnw-installer
spec:
  backoffLimit: 4
  template:
    spec:
      serviceAccountName: cnw-installer
      containers:
      - name: worker
        image: quay.io/cvicensa/cnw-installer:ocp-4.3
        env:
        - name: KUBECONFIG
          value: "/tmp/config"
        command:
        - sh
        - -c
        - ./preparelab_cnw.sh -p provision-basic.yml
        imagePullPolicy: Always
      restartPolicy: Never