apiVersion: batch/v1
kind: Job
metadata:
  name: cnw-installer
spec:
  backoffLimit: 4
  template:
    spec:
      serviceAccountName: cnw-installer
      containers:
      - name: worker
        image: quay.io/cvicensa/cnw-installer:v0.0.2
        env:
        - name: GUIDE_NAME
          value: "_cloud-native-workshop-maven.yml"
        - name: COUNT
          value: "20"
        - name: KUBECONFIG
          value: "/tmp/config"
        command:
        - sh
        - -c
        - ./preparelab_cnw.sh -g ${GUIDE_NAME} -c ${COUNT}
        imagePullPolicy: Always
      restartPolicy: Never