---
dependencies: []
allow_duplicates: true

galaxy_info:
  role_name: openshift-sonarqube
  author: Carlos Vicens
  description: Sonarqube for OpenShift
  company: "Red Hat"
  license: "license (BSD, MIT)"
  min_ansible_version: 2.3
  platforms:
  - name: GenericLinux
    versions:
    - any
  galaxy_tags:
    - openshift
    - cicd
    - sonarqube