---

deploy_jenkins: true
update_jenkins_templates: false

jenkins_template_disable_admin_monitors: false

project_name: jenkins
project_display_name: Jenkins
project_desc: Jenkins CI Engine
# project_annotations:

openshift_cli: oc

jenkins_max_mem: 2Gi
jenkins_min_mem: 512Mi

jenkins_max_cpu: 1
jenkins_min_cpu: 200m

jenkins_image_tag: 2

jenkins_service_name: jenkins

ephemeral: true