---
gogs_image_version: 0.11.29
gogs_database_image_version: 10

gogs_route: gogs-{{ project_name }}.127.0.0.1.nip.io

gogs_admin_user: gogs
gogs_admin_password: gogs

gogs_user: developer
gogs_password: developer

gogs_generate_user_count: 0
gogs_generate_user_format: user%02d

project_name: gogs
project_display_name: Gogs
project_desc: Gogs Git Server
# project_annotations:

openshift_cli: oc

gogs_deploy_retry_delay: 30
gogs_deploy_retry_count: 10

ephemeral: false
clean_deploy: false # remove existing gogs container

gogs_service_name: gogs

skip_tls_verify: true

max_mem: 512Mi
min_mem: 128Mi
max_cpu: 400m
min_cpu: 100m