- name: cloudnative-workshop-apb playbook to provision the application
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    openshift_user: 
    openshift_password: 
    openshift_token:
    openshift_master_url: 
    openshift_user_password:
    labs_project_suffix: "-XX"
    labs_guide_name:
    labs_che_guide_name:
    labs_github_account: redhat-developer-adoption-emea
    labs_github_repo: cloud-native-guides
    labs_github_ref: ocp-3.10
    gogs_dev_user: developer
    gogs_pwd: openshift
    infrasvcs_adm_user: adminuser
    infrasvcs_adm_pwd: adminpwd
    kamel_demos_namespace: "camel-k-demos"

  roles:
  - role: ansible.kubernetes-modules
    install_python_requirements: no
  #- role: ansibleplaybookbundle.asb-modules

  tasks:    
  - name: extract app route suffix from openshift-console
    block:
      - shell: "oc get route console -n openshift-console -o 'jsonpath={.spec.host}'"
        register: console_route
      - set_fact:
          console_url: "https://{{ console_route.stdout }}"
          apps_hostname_suffix: "{{ console_route.stdout |regex_replace('^console-openshift-console\\.(.*)$', '\\1') }}"
    tags: always

  - name: extract oauth route
    block:
      - shell: "oc get route oauth-openshift -n openshift-authentication -o 'jsonpath={.spec.host}'"
        register: oauth_route
      - set_fact:
          oauth_url: "https://{{ oauth_route.stdout }}"
    tags: always

  - name: delete project quota
    shell: "oc delete limitrange --all -n {{ infra_namespace }}"
    ignore_errors: true
    tags: always

  # deploy gogs
  - import_role:
      name: cnw_gogs
    vars:
      project_name: "{{ infra_namespace }}"
      gogs_route: "gogs-{{ infra_namespace }}.{{ apps_hostname_suffix }}"
      gogs_image_version: 0.11.34
      gogs_database_image_version: 10
      gogs_admin_user: "{{ infrasvcs_adm_user }}"
      gogs_admin_password: "{{ infrasvcs_adm_pwd }}"
      gogs_user: "{{ gogs_dev_user }}"
      gogs_password: "{{ gogs_pwd }}"
      gogs_generate_user_count: "{{ user_count|int }}"
      gogs_generate_user_format: "user%d"
      modules_list: "{{ guides_modules.split(',') }}"
    tags: gogs

  # deploy nexus
  - import_role:
      name: openshift_sonatype_nexus
    vars:
      project_name: "{{ infra_namespace }}"
      nexus_image_version: 3.12.1
      nexus_max_memory: 6Gi
    tags: nexus

  # Deploy sonarqube
  - import_role:
      name: openshift_sonarqube
    vars:
      project_name: "{{ infra_namespace }}"
      sonarqube_image_version: 7.0
      sonarqube_max_memory: 6Gi
    tags: sonarqube

  # deploy guides
  - import_role:
      name: openshift_workshopper
      allow_duplicates: true
    vars:
      workshopper_name: guides
      project_name: "{{ infra_namespace }}"
      workshopper_content_url_prefix: "https://raw.githubusercontent.com/{{ labs_github_account }}/{{ labs_github_repo }}/{{ labs_github_ref }}"
      workshopper_workshop_urls: "https://raw.githubusercontent.com/{{ labs_github_account }}/{{ labs_github_repo }}/{{ labs_github_ref }}/{{ labs_guide_name }}"
      workshopper_env_vars:
        PROJECT_SUFFIX: "{{ labs_project_suffix }}"
        COOLSTORE_PROJECT: coolstore
        OPENSHIFT_CONSOLE_URL: "{{ openshift_master_url }}"
        ECLIPSE_CHE_URL: http://che-{{ workspaces_namespace }}.{{ apps_hostname_suffix }}
        GIT_URL: http://gogs-{{ infra_namespace }}.{{ apps_hostname_suffix }}
        NEXUS_URL: http://nexus-{{ infra_namespace }}.{{ apps_hostname_suffix }}
    tags: guides

  # deploy guides
  - import_role:
      name: cnw_guides
    vars:
      workshopper_name: guides
      project_name: "{{ guides_namespace }}"
      master_url: "{{ openshift_master_url }}"
      console_url:
      eclipse_che_url: "http://che-{{ workspaces_namespace }}.{{ apps_hostname_suffix }}"
      keycloak_url: "http://keycloak-{{ workspaces_namespace }}.{{ apps_hostname_suffix }}"
      git_url: "http://gogs-{{ infra_namespace }}.{{ apps_hostname_suffix }}"
      external_guides_git_base_url: "https://raw.githubusercontent.com/rh-cloud-native-workshops/cloud-native-workshop-v2"
      rhamt_url: "http://rhamt-{{ rhamt_namespace }}.{{ apps_hostname_suffix }}"
      route_subdomain: "{{ apps_hostname_suffix }}"
      user_password: "{{ openshift_user_password }}"
      workshopper_modules: "{{ guides_modules.split(',') }}"
      gogs_route: "gogs.{{ infra_namespace }}:3000"
    tags: guides

  # deploy red hat application migration toolkit (web console)
  - import_role:
      name: cnw_rhamt
    vars:
      project_name: "{{ rhamt_namespace }}"
      user_password: "{{ openshift_user_password }}"
      user_count: "{{ user_count }}"
    tags: rhamt

  # install openjdk imagestream
  - name: get openjdk image stream
    shell: "oc get is java -n openshift"
    register: java_imagestream_result
    ignore_errors: true
    tags: jdk

  - name: install java image stream
    shell: "oc apply -n openshift -f https://raw.githubusercontent.com/jboss-openshift/application-templates/master/openjdk/openjdk18-image-stream.json"
    when: java_imagestream_result is failed
    tags: jdk

  # update jenkins templates
  - import_role:
      name: openshift_jenkins
    vars:
      update_jenkins_templates: true
      jenkins_template_disable_admin_monitors: true
      deploy_jenkins: false
      jenkins_max_cpu: 2
      jenkins_max_mem: 2Gi

  # deploy monitoring
  - import_role:
      name: cnw_monitoring
    vars:
      project_name: "{{ monitoring_namespace }}"
    tags: monitoring

  # deploy etherpad
  - import_role:
      name: cnw_etherpad
    vars:
      project_name: "{{ etherpad_namespace }}"
    tags: etherpad

  # deploy code ready workspaces
  - import_role:
      name: cnw_workspaces
    vars:
      project_name: "{{ workspaces_namespace }}"
    tags: code-ready-workspaces

  # deploy pipelines
  - import_role:
      name: cnw_pipelines
    tags: tekton
  
  # deploy kafka operator
  - import_role:
      name: cnw_kafka
    tags: kafka

  # deploy kamel
  - import_role:
      name: cnw_kamel
    vars:
      project_name: "{{ kamel_demos_namespace }}"
    tags: kamel

  # deploy logging
  - import_role:
      name: cnw_logging
    tags: logging

  # deploy launcher
  - import_role:
      name: cnw_launcher
    vars:
      project_name: "{{ launcher_namespace }}"
      console_url: "{{ console_url }}"
      oauth_url: "{{ oauth_url }}"
    tags: launcher

  # deploy serverless
  - import_role:
      name: cnw_serverless
    tags: serverless