all_namespaces_project_name: openshift-operators

kafka_subsription_channel: stable
kafka_subsription_install_plan_approval: Automatic
kafka_subsription_name: amq-streams
kafka_subsription_source: redhat-operators
kafka_subsription_source_namespace: openshift-marketplace
kafka_subsription_starting_csv: amqstreams.v1.3.0

kafka_subsription_csv_root: amqstreams
